// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorCode.
const (
	AUTOMATIONPERMISSIONDENIED ErrorCode = "AUTOMATION_PERMISSION_DENIED"
	CATALOGUNAVAILABLE         ErrorCode = "CATALOG_UNAVAILABLE"
	MICROPHONEPERMISSIONDENIED ErrorCode = "MICROPHONE_PERMISSION_DENIED"
	MODELUNAVAILABLE           ErrorCode = "MODEL_UNAVAILABLE"
	MUSICAPPNOTRUNNING         ErrorCode = "MUSIC_APP_NOT_RUNNING"
	NOMATCHFOUND               ErrorCode = "NO_MATCH_FOUND"
	NOMATCHINGTRACKS           ErrorCode = "NO_MATCHING_TRACKS"
	NOTFOUND                   ErrorCode = "NOT_FOUND"
	SYNCINPROGRESS             ErrorCode = "SYNC_IN_PROGRESS"
	TRACKNOTAVAILABLELOCALLY   ErrorCode = "TRACK_NOT_AVAILABLE_LOCALLY"
	TURNALREADYRUNNING         ErrorCode = "TURN_ALREADY_RUNNING"
	VALIDATIONFAILED           ErrorCode = "VALIDATION_FAILED"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case AUTOMATIONPERMISSIONDENIED:
		return true
	case CATALOGUNAVAILABLE:
		return true
	case MICROPHONEPERMISSIONDENIED:
		return true
	case MODELUNAVAILABLE:
		return true
	case MUSICAPPNOTRUNNING:
		return true
	case NOMATCHFOUND:
		return true
	case NOMATCHINGTRACKS:
		return true
	case NOTFOUND:
		return true
	case SYNCINPROGRESS:
		return true
	case TRACKNOTAVAILABLELOCALLY:
		return true
	case TURNALREADYRUNNING:
		return true
	case VALIDATIONFAILED:
		return true
	default:
		return false
	}
}

// Defines values for QueueItemOrigin.
const (
	QueueItemOriginAgent       QueueItemOrigin = "agent"
	QueueItemOriginGeneration  QueueItemOrigin = "generation"
	QueueItemOriginManual      QueueItemOrigin = "manual"
	QueueItemOriginRecognition QueueItemOrigin = "recognition"
	QueueItemOriginRevive      QueueItemOrigin = "revive"
)

// Valid indicates whether the value is a known member of the QueueItemOrigin enum.
func (e QueueItemOrigin) Valid() bool {
	switch e {
	case QueueItemOriginAgent:
		return true
	case QueueItemOriginGeneration:
		return true
	case QueueItemOriginManual:
		return true
	case QueueItemOriginRecognition:
		return true
	case QueueItemOriginRevive:
		return true
	default:
		return false
	}
}

// Defines values for QueueItemState.
const (
	Pending QueueItemState = "pending"
	Played  QueueItemState = "played"
	Playing QueueItemState = "playing"
	Removed QueueItemState = "removed"
	Skipped QueueItemState = "skipped"
)

// Valid indicates whether the value is a known member of the QueueItemState enum.
func (e QueueItemState) Valid() bool {
	switch e {
	case Pending:
		return true
	case Played:
		return true
	case Playing:
		return true
	case Removed:
		return true
	case Skipped:
		return true
	default:
		return false
	}
}

// Defines values for ReactionDetector.
const (
	Poll ReactionDetector = "poll"
	User ReactionDetector = "user"
)

// Valid indicates whether the value is a known member of the ReactionDetector enum.
func (e ReactionDetector) Valid() bool {
	switch e {
	case Poll:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for ReactionType.
const (
	Complete         ReactionType = "complete"
	Dislike          ReactionType = "dislike"
	ExplicitNegative ReactionType = "explicit_negative"
	ExplicitPositive ReactionType = "explicit_positive"
	Favorite         ReactionType = "favorite"
	Repeat           ReactionType = "repeat"
	SkipEarly        ReactionType = "skip_early"
	SkipMid          ReactionType = "skip_mid"
)

// Valid indicates whether the value is a known member of the ReactionType enum.
func (e ReactionType) Valid() bool {
	switch e {
	case Complete:
		return true
	case Dislike:
		return true
	case ExplicitNegative:
		return true
	case ExplicitPositive:
		return true
	case Favorite:
		return true
	case Repeat:
		return true
	case SkipEarly:
		return true
	case SkipMid:
		return true
	default:
		return false
	}
}

// Defines values for SessionStatus.
const (
	Active SessionStatus = "active"
	Ended  SessionStatus = "ended"
)

// Valid indicates whether the value is a known member of the SessionStatus enum.
func (e SessionStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Ended:
		return true
	default:
		return false
	}
}

// Defines values for SyncStatus.
const (
	SyncStatusFailed    SyncStatus = "failed"
	SyncStatusRunning   SyncStatus = "running"
	SyncStatusSucceeded SyncStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the SyncStatus enum.
func (e SyncStatus) Valid() bool {
	switch e {
	case SyncStatusFailed:
		return true
	case SyncStatusRunning:
		return true
	case SyncStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for TagKind.
const (
	Context TagKind = "context"
	Energy  TagKind = "energy"
	Mood    TagKind = "mood"
)

// Valid indicates whether the value is a known member of the TagKind enum.
func (e TagKind) Valid() bool {
	switch e {
	case Context:
		return true
	case Energy:
		return true
	case Mood:
		return true
	default:
		return false
	}
}

// Defines values for TrackSource.
const (
	File   TrackSource = "file"
	Shared TrackSource = "shared"
)

// Valid indicates whether the value is a known member of the TrackSource enum.
func (e TrackSource) Valid() bool {
	switch e {
	case File:
		return true
	case Shared:
		return true
	default:
		return false
	}
}

// Defines values for TurnIntent.
const (
	Explain       TurnIntent = "explain"
	GenerateQueue TurnIntent = "generate_queue"
	React         TurnIntent = "react"
	RefineQueue   TurnIntent = "refine_queue"
	Unknown       TurnIntent = "unknown"
)

// Valid indicates whether the value is a known member of the TurnIntent enum.
func (e TurnIntent) Valid() bool {
	switch e {
	case Explain:
		return true
	case GenerateQueue:
		return true
	case React:
		return true
	case RefineQueue:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for TurnStatus.
const (
	TurnStatusCancelled TurnStatus = "cancelled"
	TurnStatusFailed    TurnStatus = "failed"
	TurnStatusQueued    TurnStatus = "queued"
	TurnStatusRunning   TurnStatus = "running"
	TurnStatusSucceeded TurnStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the TurnStatus enum.
func (e TurnStatus) Valid() bool {
	switch e {
	case TurnStatusCancelled:
		return true
	case TurnStatusFailed:
		return true
	case TurnStatusQueued:
		return true
	case TurnStatusRunning:
		return true
	case TurnStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for ListTracksParamsFilter.
const (
	All            ListTracksParamsFilter = "all"
	Excluded       ListTracksParamsFilter = "excluded"
	NeverPlayed    ListTracksParamsFilter = "never_played"
	NotPlayedSince ListTracksParamsFilter = "not_played_since"
)

// Valid indicates whether the value is a known member of the ListTracksParamsFilter enum.
func (e ListTracksParamsFilter) Valid() bool {
	switch e {
	case All:
		return true
	case Excluded:
		return true
	case NeverPlayed:
		return true
	case NotPlayedSince:
		return true
	default:
		return false
	}
}

// Defines values for ListTracksParamsSort.
const (
	AddedAtDesc     ListTracksParamsSort = "added_at_desc"
	LastPlayedAtAsc ListTracksParamsSort = "last_played_at_asc"
	PlayCountAsc    ListTracksParamsSort = "play_count_asc"
	TitleAsc        ListTracksParamsSort = "title_asc"
)

// Valid indicates whether the value is a known member of the ListTracksParamsSort enum.
func (e ListTracksParamsSort) Valid() bool {
	switch e {
	case AddedAtDesc:
		return true
	case LastPlayedAtAsc:
		return true
	case PlayCountAsc:
		return true
	case TitleAsc:
		return true
	default:
		return false
	}
}

// AddLibraryTrackRequest defines model for AddLibraryTrackRequest.
type AddLibraryTrackRequest struct {
	AppleMusicId string `json:"appleMusicId"`

	// EnqueueToSessionId 지정하면 추가 후 곧바로 이 세션의 큐에 넣는다
	EnqueueToSessionId *int64 `json:"enqueueToSessionId,omitempty"`
}

// Album defines model for Album.
type Album struct {
	Artist      Artist  `json:"artist"`
	ArtworkUrl  *string `json:"artworkUrl,omitempty"`
	Id          int64   `json:"id"`
	ReleaseYear *int    `json:"releaseYear,omitempty"`
	Title       string  `json:"title"`
}

// Artist defines model for Artist.
type Artist struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

// CatalogTrack Apple Music 카탈로그의 곡. 아직 라이브러리에 없을 수 있다
type CatalogTrack struct {
	AlbumName    *string `json:"albumName,omitempty"`
	AppleMusicId string  `json:"appleMusicId"`
	ArtistName   string  `json:"artistName"`
	ArtworkUrl   *string `json:"artworkUrl,omitempty"`
	Genre        *string `json:"genre,omitempty"`

	// InLibrary 이미 라이브러리에 있는지 여부
	InLibrary *bool   `json:"inLibrary,omitempty"`
	Isrc      *string `json:"isrc,omitempty"`
	Title     string  `json:"title"`
	Year      *int    `json:"year,omitempty"`
}

// CreatePlaylistRequest defines model for CreatePlaylistRequest.
type CreatePlaylistRequest struct {
	Name string `json:"name"`

	// SessionId 이 세션의 큐를 그대로 저장한다
	SessionId int64 `json:"sessionId"`
}

// CreateQueueItemRequest defines model for CreateQueueItemRequest.
type CreateQueueItemRequest struct {
	// Origin 누가 이 곡을 큐에 넣었는지. `agent` 는 AI 에이전트가 API 로 직접
	// 투입한 경우이며, 사람이 고른 것과 구분해 측정하기 위해 남긴다.
	Origin *QueueItemOrigin `json:"origin,omitempty"`

	// Position 생략하면 큐 끝에 붙인다
	Position *int  `json:"position,omitempty"`
	TrackId  int64 `json:"trackId"`
}

// CreateReactionRequest defines model for CreateReactionRequest.
type CreateReactionRequest struct {
	// DetectedBy `poll` 은 재생 위치 폴링이 관찰한 것 (기본)
	DetectedBy  *ReactionDetector `json:"detectedBy,omitempty"`
	PositionSec *float32          `json:"positionSec,omitempty"`
	Type        ReactionType      `json:"type"`
}

// CreateRecognitionRequest ShazamKit 헬퍼가 반환한 `SHMediaItem` 을 그대로 옮긴다
type CreateRecognitionRequest struct {
	AppleMusicId *string `json:"appleMusicId,omitempty"`
	ArtistName   string  `json:"artistName"`
	ArtworkUrl   *string `json:"artworkUrl,omitempty"`
	Genre        *string `json:"genre,omitempty"`
	Isrc         *string `json:"isrc,omitempty"`
	SessionId    *int64  `json:"sessionId,omitempty"`
	ShazamId     string  `json:"shazamId"`
	Title        string  `json:"title"`
	Year         *int    `json:"year,omitempty"`
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	// Prompt 함께 보내면 첫 턴을 즉시 시작한다
	//
	// Example: 새벽 코딩용, 가사 없는 걸로
	Prompt *string `json:"prompt,omitempty"`
	Title  *string `json:"title,omitempty"`
}

// CreateTurnRequest defines model for CreateTurnRequest.
type CreateTurnRequest struct {
	// MentionedArtistIds `@` 멘션으로 후보를 좁힌 경우
	MentionedArtistIds *[]int64 `json:"mentionedArtistIds,omitempty"`
	MentionedTrackIds  *[]int64 `json:"mentionedTrackIds,omitempty"`

	// Prompt Example: 좀 더 조용한 걸로
	Prompt string `json:"prompt"`
}

// Error defines model for Error.
type Error struct {
	// Code 화면 예외 E1~E10 에 대응한다
	Code ErrorCode `json:"code"`

	// Hint 조치 안내. 화면 하단에 함께 표시된다
	Hint *string `json:"hint,omitempty"`

	// Message 사용자에게 그대로 보여줄 수 있는 문장
	Message string `json:"message"`
}

// ErrorCode 화면 예외 E1~E10 에 대응한다
type ErrorCode string

// LibraryDiagnosis S3 진단 화면. 서비스의 문제 정의를 사용자 데이터로 증명한다
type LibraryDiagnosis struct {
	// FileTrackCount 로컬 파일 곡 수
	FileTrackCount *int     `json:"fileTrackCount,omitempty"`
	LastSync       *SyncRun `json:"lastSync,omitempty"`

	// NeverPlayedCount `lastPlayedAt` 이 `null` 인 곡 수
	//
	// Example: 57
	NeverPlayedCount int `json:"neverPlayedCount"`

	// NeverPlayedRatio 0.0 ~ 1.0
	//
	// Example: 0.363
	NeverPlayedRatio float32 `json:"neverPlayedRatio"`

	// OldestLastPlayedAt 전곡이 미재생이면 `null`
	OldestLastPlayedAt *time.Time `json:"oldestLastPlayedAt,omitempty"`

	// PlayedLast30DaysCount Example: 52
	PlayedLast30DaysCount int `json:"playedLast30DaysCount"`

	// PlayedLast365DaysCount Example: 100
	PlayedLast365DaysCount int `json:"playedLast365DaysCount"`

	// SharedTrackCount Apple Music 스트리밍 곡 수
	SharedTrackCount *int `json:"sharedTrackCount,omitempty"`

	// TotalTracks Example: 157
	TotalTracks int `json:"totalTracks"`

	// UntaggedCount L1 태깅이 아직 안 된 곡 수
	UntaggedCount *int `json:"untaggedCount,omitempty"`
}

// PageMeta defines model for PageMeta.
type PageMeta struct {
	HasMore    bool    `json:"hasMore"`
	NextCursor *string `json:"nextCursor,omitempty"`
}

// Playlist defines model for Playlist.
type Playlist struct {
	// AppleMusicPlaylistId Music.app 반영 실패 시 `null` 로 남는다
	AppleMusicPlaylistId *string   `json:"appleMusicPlaylistId,omitempty"`
	CreatedAt            time.Time `json:"createdAt"`
	Id                   int64     `json:"id"`
	Name                 string    `json:"name"`
	SourceSessionId      *int64    `json:"sourceSessionId,omitempty"`
	TrackCount           int       `json:"trackCount"`
}

// QueueItem defines model for QueueItem.
type QueueItem struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	Id        int64      `json:"id"`

	// Origin 누가 이 곡을 큐에 넣었는지. `agent` 는 AI 에이전트가 API 로 직접
	// 투입한 경우이며, 사람이 고른 것과 구분해 측정하기 위해 남긴다.
	Origin   QueueItemOrigin `json:"origin"`
	Position int             `json:"position"`

	// Reason ★ F2 선정 근거 한 줄. L4 실패 시 `null` 이며 재생은 계속된다
	//
	// Example: 담아둔 뒤 한 번도 재생한 적 없고, 가사가 없습니다
	Reason    *string        `json:"reason,omitempty"`
	SessionId int64          `json:"sessionId"`
	State     QueueItemState `json:"state"`
	Track     Track          `json:"track"`
}

// QueueItemOrigin 누가 이 곡을 큐에 넣었는지. `agent` 는 AI 에이전트가 API 로 직접
// 투입한 경우이며, 사람이 고른 것과 구분해 측정하기 위해 남긴다.
type QueueItemOrigin string

// QueueItemState defines model for QueueItemState.
type QueueItemState string

// QueueSummary S1 상태줄의 큐 요약
type QueueSummary struct {
	// NeverPlayedCount 큐 안에서 `lastPlayedAt` 이 `null` 인 곡 수
	NeverPlayedCount int `json:"neverPlayedCount"`
	TotalDurationMs  int `json:"totalDurationMs"`
	TrackCount       int `json:"trackCount"`
}

// Reaction defines model for Reaction.
type Reaction struct {
	CreatedAt time.Time `json:"createdAt"`

	// DetectedBy `poll` 은 재생 위치 폴링이 관찰한 것 (기본)
	DetectedBy ReactionDetector `json:"detectedBy"`
	Id         int64            `json:"id"`

	// PositionSec 이탈 시점. `skip_early` 판정 근거
	PositionSec *float32     `json:"positionSec,omitempty"`
	QueueItemId int64        `json:"queueItemId"`
	Type        ReactionType `json:"type"`
}

// ReactionDetector `poll` 은 재생 위치 폴링이 관찰한 것 (기본)
type ReactionDetector string

// ReactionType defines model for ReactionType.
type ReactionType string

// Recognition defines model for Recognition.
type Recognition struct {
	AppleMusicId *string `json:"appleMusicId,omitempty"`
	ArtistName   string  `json:"artistName"`
	ArtworkUrl   *string `json:"artworkUrl,omitempty"`
	Genre        *string `json:"genre,omitempty"`
	Id           int64   `json:"id"`
	Isrc         *string `json:"isrc,omitempty"`

	// MatchedTrack ★ F11. `null` 이면 라이브러리에 없는 곡이다.
	// 채워져 있고 그 곡의 `lastPlayedAt` 이 `null` 이면
	// **담아두고 한 번도 듣지 않은 곡**이다.
	MatchedTrack *Track    `json:"matchedTrack,omitempty"`
	RecognizedAt time.Time `json:"recognizedAt"`
	SessionId    *int64    `json:"sessionId,omitempty"`
	ShazamId     string    `json:"shazamId"`
	Title        string    `json:"title"`
	Year         *int      `json:"year,omitempty"`
}

// Session defines model for Session.
type Session struct {
	EndedAt *time.Time `json:"endedAt,omitempty"`
	Id      int64      `json:"id"`

	// Prompt 최초 자연어 입력 원문
	Prompt     string        `json:"prompt"`
	QueueItems *[]QueueItem  `json:"queueItems,omitempty"`
	StartedAt  time.Time     `json:"startedAt"`
	Status     SessionStatus `json:"status"`

	// Summary S1 상태줄의 큐 요약
	Summary *QueueSummary `json:"summary,omitempty"`

	// Title 최초 요청에서 생성. S1 헤더에 표시된다
	Title      string `json:"title"`
	TrackCount *int   `json:"trackCount,omitempty"`

	// Usage S1 상태줄에 표시되는 누적 사용량
	Usage Usage `json:"usage"`
}

// SessionStatus defines model for SessionStatus.
type SessionStatus string

// SessionSummary defines model for SessionSummary.
type SessionSummary struct {
	EndedAt   *time.Time    `json:"endedAt,omitempty"`
	Id        int64         `json:"id"`
	StartedAt time.Time     `json:"startedAt"`
	Status    SessionStatus `json:"status"`

	// Title 최초 요청에서 생성. S1 헤더에 표시된다
	Title      string `json:"title"`
	TrackCount *int   `json:"trackCount,omitempty"`
}

// SyncRun defines model for SyncRun.
type SyncRun struct {
	Error      *Error     `json:"error,omitempty"`
	FinishedAt *time.Time `json:"finishedAt,omitempty"`
	Id         int64      `json:"id"`
	StartedAt  time.Time  `json:"startedAt"`
	Status     SyncStatus `json:"status"`

	// TaggedCount L1 무드 태깅이 완료된 곡 수
	TaggedCount *int `json:"taggedCount,omitempty"`
	TrackCount  *int `json:"trackCount,omitempty"`
}

// SyncStatus defines model for SyncStatus.
type SyncStatus string

// Tag defines model for Tag.
type Tag struct {
	// Confidence 해당 곡에 부여된 신뢰도 (L1 산출)
	Confidence *float32 `json:"confidence,omitempty"`
	Id         int64    `json:"id"`
	Kind       TagKind  `json:"kind"`

	// Name Example: 새벽
	Name string `json:"name"`
}

// TagKind defines model for Tag.Kind.
type TagKind string

// TasteRule defines model for TasteRule.
type TasteRule struct {
	Active bool `json:"active"`

	// Condition L3 선곡이 소비하는 구조화 조건
	Condition map[string]interface{} `json:"condition"`
	DerivedAt time.Time              `json:"derivedAt"`

	// EvidenceCount 근거가 된 반응 수. S4 에 함께 표시된다
	EvidenceCount int   `json:"evidenceCount"`
	Id            int64 `json:"id"`

	// Statement Example: 새벽 시간대에 가사 있는 곡을 회피
	Statement string     `json:"statement"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// Track defines model for Track.
type Track struct {
	// AddedAt 라이브러리에 담은 시각. **라이브러리에 없는 곡(`inLibrary=false`)은
	// `null`** 이다 — 담은 적이 없으므로 담은 날짜도 없다.
	// 없는 값을 채워 넣으면 선정 근거가 사실이 아니게 된다.
	AddedAt      *time.Time `json:"addedAt,omitempty"`
	Album        *Album     `json:"album,omitempty"`
	AppleMusicId *string    `json:"appleMusicId,omitempty"`
	Artist       Artist     `json:"artist"`

	// CloudStatus Example: subscription
	CloudStatus *string `json:"cloudStatus,omitempty"`
	Disliked    bool    `json:"disliked"`
	DurationMs  int     `json:"durationMs"`

	// Excluded 정리 표시된 곡. 큐 후보에서 제외된다
	Excluded  bool    `json:"excluded"`
	Favorited bool    `json:"favorited"`
	Genre     *string `json:"genre,omitempty"`
	Id        int64   `json:"id"`

	// InLibrary 사용자 라이브러리에 담긴 곡인지. 플레이리스트에만 담고
	// 라이브러리에는 추가하지 않은 곡이 실제로 존재하므로 구분한다.
	// `false` 인 곡은 Songs·Artists·Albums 목록에 나오지 않는다.
	InLibrary bool    `json:"inLibrary"`
	Isrc      *string `json:"isrc,omitempty"`

	// LastPlayedAt ★ `null` 이면 **담아두고 한 번도 재생하지 않은 곡**이다. 묘비의 1차 기준
	LastPlayedAt  *time.Time `json:"lastPlayedAt,omitempty"`
	LastSkippedAt *time.Time `json:"lastSkippedAt,omitempty"`

	// PersistentId Music.app 동기화 키
	PersistentId *string `json:"persistentId,omitempty"`
	PlayCount    int     `json:"playCount"`
	Rating       *int    `json:"rating,omitempty"`
	SkipCount    int     `json:"skipCount"`

	// Source `shared` 는 Apple Music 스트리밍. 실측 라이브러리의 97%
	Source TrackSource `json:"source"`
	Tags   *[]Tag      `json:"tags,omitempty"`
	Title  string      `json:"title"`
	Year   *int        `json:"year,omitempty"`
}

// TrackSource `shared` 는 Apple Music 스트리밍. 실측 라이브러리의 97%
type TrackSource string

// Turn defines model for Turn.
type Turn struct {
	// AssistantMessage 사용자에게 보여줄 응답 문장
	AssistantMessage *string   `json:"assistantMessage,omitempty"`
	CreatedAt        time.Time `json:"createdAt"`

	// Error `failed` 일 때의 사유. 이 경우에도 기존 큐의 재생은 계속된다
	Error      *Error     `json:"error,omitempty"`
	FinishedAt *time.Time `json:"finishedAt,omitempty"`
	Id         int64      `json:"id"`

	// Intent 분류 전에는 `null`
	Intent *TurnIntent `json:"intent,omitempty"`
	Prompt string      `json:"prompt"`

	// QueueItems `succeeded` 일 때 생성·변경된 큐 항목
	QueueItems *[]QueueItem `json:"queueItems,omitempty"`
	SessionId  int64        `json:"sessionId"`
	Status     TurnStatus   `json:"status"`
	Usage      *Usage       `json:"usage,omitempty"`
}

// TurnIntent L2 가 분류한 의도
type TurnIntent string

// TurnStatus defines model for TurnStatus.
type TurnStatus string

// UpdateQueueItemRequest defines model for UpdateQueueItemRequest.
type UpdateQueueItemRequest struct {
	Position *int            `json:"position,omitempty"`
	State    *QueueItemState `json:"state,omitempty"`
}

// UpdateSessionRequest defines model for UpdateSessionRequest.
type UpdateSessionRequest struct {
	Status *SessionStatus `json:"status,omitempty"`
	Title  *string        `json:"title,omitempty"`
}

// UpdateTasteRuleRequest defines model for UpdateTasteRuleRequest.
type UpdateTasteRuleRequest struct {
	Active    *bool   `json:"active,omitempty"`
	Statement *string `json:"statement,omitempty"`
}

// UpdateTrackRequest 묘비 화면의 "정리" — 제외 표시만 바꾼다. 곡을 삭제하지 않는다
type UpdateTrackRequest struct {
	Excluded *bool `json:"excluded,omitempty"`
}

// Usage S1 상태줄에 표시되는 누적 사용량
type Usage struct {
	CompletionTokens int     `json:"completionTokens"`
	CostUsd          float64 `json:"costUsd"`
	PromptTokens     int     `json:"promptTokens"`
}

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int

// QueueItemId defines model for QueueItemId.
type QueueItemId = int64

// RecognitionId defines model for RecognitionId.
type RecognitionId = int64

// SessionId defines model for SessionId.
type SessionId = int64

// SyncRunId defines model for SyncRunId.
type SyncRunId = int64

// TasteRuleId defines model for TasteRuleId.
type TasteRuleId = int64

// TrackId defines model for TrackId.
type TrackId = int64

// TurnId defines model for TurnId.
type TurnId = int64

// BadGateway defines model for BadGateway.
type BadGateway = Error

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = Error

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = Error

// ListArtistsParams defines parameters for ListArtists.
type ListArtistsParams struct {
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Limit 한 번에 가져올 개수
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListSyncRunsParams defines parameters for ListSyncRuns.
type ListSyncRunsParams struct {
	// Limit 한 번에 가져올 개수
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor 다음 페이지 커서
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListPlaylistsParams defines parameters for ListPlaylists.
type ListPlaylistsParams struct {
	// Limit 한 번에 가져올 개수
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor 다음 페이지 커서
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListRecognitionsParams defines parameters for ListRecognitions.
type ListRecognitionsParams struct {
	// Limit 한 번에 가져올 개수
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor 다음 페이지 커서
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListSessionsParams defines parameters for ListSessions.
type ListSessionsParams struct {
	Status *SessionStatus `form:"status,omitempty" json:"status,omitempty"`

	// Limit 한 번에 가져올 개수
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor 다음 페이지 커서
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListTurnsParams defines parameters for ListTurns.
type ListTurnsParams struct {
	// Limit 한 번에 가져올 개수
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor 다음 페이지 커서
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListTasteRulesParams defines parameters for ListTasteRules.
type ListTasteRulesParams struct {
	Active *bool `form:"active,omitempty" json:"active,omitempty"`

	// Limit 한 번에 가져올 개수
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor 다음 페이지 커서
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListTracksParams defines parameters for ListTracks.
type ListTracksParams struct {
	// Filter 조회 기준
	Filter *ListTracksParamsFilter `form:"filter,omitempty" json:"filter,omitempty"`

	// Since `filter=not_played_since` 일 때의 기준일
	Since *openapi_types.Date `form:"since,omitempty" json:"since,omitempty"`

	// Q 제목·아티스트 부분 일치
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Tag 태그명으로 필터 (복수 지정 시 AND)
	Tag  *[]string             `form:"tag,omitempty" json:"tag,omitempty"`
	Sort *ListTracksParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Limit 한 번에 가져올 개수
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor 다음 페이지 커서
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListTracksParamsFilter defines parameters for ListTracks.
type ListTracksParamsFilter string

// ListTracksParamsSort defines parameters for ListTracks.
type ListTracksParamsSort string

// ListSimilarCatalogTracksParams defines parameters for ListSimilarCatalogTracks.
type ListSimilarCatalogTracksParams struct {
	// Limit 한 번에 가져올 개수
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// AddLibraryTrackJSONRequestBody defines body for AddLibraryTrack for application/json ContentType.
type AddLibraryTrackJSONRequestBody = AddLibraryTrackRequest

// CreatePlaylistJSONRequestBody defines body for CreatePlaylist for application/json ContentType.
type CreatePlaylistJSONRequestBody = CreatePlaylistRequest

// UpdateQueueItemJSONRequestBody defines body for UpdateQueueItem for application/json ContentType.
type UpdateQueueItemJSONRequestBody = UpdateQueueItemRequest

// CreateReactionJSONRequestBody defines body for CreateReaction for application/json ContentType.
type CreateReactionJSONRequestBody = CreateReactionRequest

// CreateRecognitionJSONRequestBody defines body for CreateRecognition for application/json ContentType.
type CreateRecognitionJSONRequestBody = CreateRecognitionRequest

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// UpdateSessionJSONRequestBody defines body for UpdateSession for application/json ContentType.
type UpdateSessionJSONRequestBody = UpdateSessionRequest

// CreateQueueItemJSONRequestBody defines body for CreateQueueItem for application/json ContentType.
type CreateQueueItemJSONRequestBody = CreateQueueItemRequest

// CreateTurnJSONRequestBody defines body for CreateTurn for application/json ContentType.
type CreateTurnJSONRequestBody = CreateTurnRequest

// UpdateTasteRuleJSONRequestBody defines body for UpdateTasteRule for application/json ContentType.
type UpdateTasteRuleJSONRequestBody = UpdateTasteRuleRequest

// UpdateTrackJSONRequestBody defines body for UpdateTrack for application/json ContentType.
type UpdateTrackJSONRequestBody = UpdateTrackRequest
